### ISSUE TITLE
ERROR: Check your directories, lamedb should be version 4.

### ISSUE THREAD

**Issue by MrOnyx** [picons/lamedb-conversion#1]
Using username "root".
root@dm8000:~# cd /tmp
root@dm8000:/var/volatile/tmp# ./lamedb2tvheadend.sh
ERROR: Check your directories, lamedb should be version 4.
USAGE: /lamedb2tvh.sh /etc/enigma2 /media/usb/tvh /picon

Press [ENTER] to exit...

**Comment by picons** [comment]
And what is your problem exactly? Is your lamedb a version 4 lamedb?

Also take into consideration that when using the latest TVH git release it might not work, because I believe some things have changed since that time.

**Comment by picons** [comment]
Oh, I see now that you are trying to run this on a DM8000, well that isn't going to work at all, please use a Linux PC OS like Ubuntu.
